abstract: Perl interface to the Amazon Elastic Compute Cloud (EC2)
author: 'Jeff Kim <jkim@chosec.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Net-Amazon-EC2
no_index:
  directory:
    - inc
    - t
requires:
  Digest::HMAC_SHA1: 0
  HTTP::Date: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Params::Validate: 0
  URI: 0
  XML::Simple: 0
version: 0.04
